url: https://guggisbergsimon.github.io/heig-pdg-2024
baseurl: /

# Site settings
title: Musicz
description: "Musicz is a brand new automation musical game as a student project."


# Team names, titles and social links
people:
- name: Olin Bourquin
  pic: 1.gif
  position: Developer
  social:
    - title: github
      url: https://github.com/OlinB

- name: Kilian Demont
  pic: 2.jpg
  position: Developer
  social:
    - title: github
      url: https://github.com/kdemont

- name: Simon Guggisberg
  pic: 3.jpg
  position: Developer
  social: 
    - title: github
      url: https://github.com/GuggisbergSimon

- name: Jonas Troeltsch
  pic: 4.jpg
  position: Developer
  social:
    - title: github
      url: https://github.com/jonas-tr

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/GuggisbergSimon/heig-pdg-2024

# Postal address (add as many lines as necessary)
address:
  - line: HEIG-VD
  - line: Yverdon-les-Bains, CH

# Build settings
markdown: kramdown
permalink: pretty