using Godot;
using heigpdg2024.scripts.resources;

namespace heigpdg2024.scripts.cells;

/// <summary>
/// Class representing a Source of notes
/// </summary>
public class Source {
    public Vector2I Output { get; }

    public Vector2 Position { get; }

    public DurationNotation Duration { get; }

    /// <summary>
    /// Source constructor
    /// </summary>
    /// <param name="position">The center position in the world of this source</param>
    /// <param name="output">The direction of the output of this source</param>
    /// <param name="duration">The duration of the note generated by this source</param>
    public Source(Vector2 position, Vector2I output, DurationNotation duration) {
        Position = position;
        Output = output;
        Duration = duration;
    }
}